Task implement start/end entry points for game loop
fadedFog/Tombs pull request #10
Opened 2021-07-22 13:00 UTC by fadedFog

2021-07-22 13:52 UTC, Agny requested changes

2021-07-22 13:52 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +				System.exit(1);
Почему `1`?

2021-07-22 13:52 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	    		changePositionUser((TreasureHunter<MoveBehavior>) value, key, key);
?

2021-07-22 13:52 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/settings/SettingsGame.java
> +	private static SettingsGame instance;
Прочитай, что делает static модификатор. Хватит уже вставлять его, где надо и не надо.

2021-07-22 13:52 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +			if (!isMainMenu) {
Это все в лапшу уже превращается. Надо как-то реорганизовать код

2021-07-22 14:30 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +				System.exit(1);
Ой, точно, почему? Всё же хорошо :D

2021-07-22 14:34 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	    		changePositionUser((TreasureHunter<MoveBehavior>) value, key, key);
Т.к. он начинает менять свою позицию по оси x. А там только гравитация действовать должна. X у ГГ меняется, когда я перемещаю его.

2021-07-22 14:38 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/settings/SettingsGame.java
> +	private static SettingsGame instance;
Я реализовал паттерн Одиночка. Через @Component + @Autowired вызывает проблемы.

2021-07-23 01:30 UTC, Agny requested changes

2021-07-23 01:30 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	private void stepOfGame() throws InterruptedException {
Мало смысла бросать это исключение дальше, если ты все равно не знаешь, что с ним делать. Лови уж тут же

2021-07-23 01:30 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		if (!isMainMenu) {
Все еще не очень выглядит. Это же условия разных по логике вещей - один про стартовое меню, второй про паузу в игре. Почему во время игры надо проверять, не в меню ли мы находимся? Надо переделать

2021-07-23 01:35 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/settings/SettingsGame.java
> +	private static SettingsGame instance;
Тут и автовайред не очень нужен был и синглтон не подходит. Идея не в том, чтобы был возможен условно единственный объект настроек, а в том, чтобы в активной сессии использовался один и тот же объект. Почувствуй разницу.

2021-07-23 01:46 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	    		changePositionUser((TreasureHunter<MoveBehavior>) value, key, key);
Настало время переименовать `value` и `key` во что-то осмысленное.
И непоследовательность какая-то - логируешь ньюкей, а потом его игнорируешь для ГГ. Смешались в кучу кони, люди. Надо переделать, чтобы было ясно - что и как относится к передвижению ГГ, а что - к передвижению всех остальных.

2021-07-23 21:03 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	private void stepOfGame() throws InterruptedException {
Так более удобно читать, чем всё в одно место сложит.

2021-07-26 22:05 UTC, Agny requested changes

2021-07-26 22:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/Immovable.java
> +	public Immovable(SettingsGame settingsGame) {
Не, давай так делать не будем. Инжектить еще куда ни шло, но в конструктор передавать совсем не годится

2021-07-26 22:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	    	if (character instanceof TreasureHunter<?>) {
Вытащи уже ссылку на гг в отдельную переменную, неудобно же так и страшно

2021-07-26 22:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		if (!isMainMenu) {
Если мусор под коврик заметать, он мусором от этого быть не перестает. Тройной вложенный if - плохо, все еще надо переделать

2021-07-26 22:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		this.roomConfig.setSettingsGame(settingsGame);
Это вообще грязь. Все привыкли к обычным сеттерам, если в них запихивать доп. функционал, то это может привести к неожиданным последствиям. Если нужно что-то подобное сделать, то метод не должен быть похож не сеттер.

2021-07-26 22:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/generate/RoomConfig.java
> +	public void setSettingsGame(SettingsGame settingsGame) {
Инжекти

2021-07-30 09:38 UTC, Agny requested changes

2021-07-30 09:38 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		if (!isMainMenu && !isPause() && isHeroLive()) {
Считаешь, стало лучше? Почитай про switch и подумай, как с его применением это все переписать. А еще почитай про state machine

2021-07-30 09:38 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/Movable.java
> +	public void setSettingsGameAndBoost(SettingsGame settingsGame) {
Это не инжектирование

2021-07-30 12:58 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		if (!isMainMenu && !isPause() && isHeroLive()) {
Не особо.

2021-07-30 14:19 UTC, Agny requested changes

2021-07-30 14:19 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/Immovable.java
> +	public void setSettingsGame(SettingsGame settingsGame) {
И зачем, если автовайред есть?

2021-07-30 14:19 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		setStateGame(StateGame.MAIN_MENU);
Почему при объявлении переменной сразу не выставить это значение?

2021-08-11 23:45 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +	private int lastKey;
?

2021-08-11 23:48 UTC, Agny requested changes

2021-08-11 23:48 UTC, Agny commented on app/src/test/java/ru/fadedfog/tombs/GameLoopTest.java
> +    }
Это ведь не все стейты. Где поражение?

2021-08-12 18:11 UTC, fadedFog commented on app/src/test/java/ru/fadedfog/tombs/GameLoopTest.java
> +    }
Блин, точняк. Чет я зацыклился на кавишах.

2021-08-18 20:58 UTC, Agny approved these changes

2021-08-19 17:12 UTC, merged