Added classes for keys interactions user(pause, movement) and view.
fadedFog/Tombs pull request #7
Opened 2021-06-02 14:26 UTC by fadedFog

2021-06-02 15:05 UTC, Agny requested changes

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +				user = (TreasureHunter<MoveBehavior>) character;
Почему не сюда return?

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public void changePositionUser(Point oldPoint, Point newPoint) {
Герой сможет передвигаться только по результату нажатия кнопки?
Если же ловушки/монстры смогут его толкать, то это передвижение будет багнутым

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +					System.out.println(newPoint);
Думаю, пора логирование прикрутить. Поменяй все систем ауты на лог.инфо для начала. Библиотеку можешь logback взять

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		characters.remove(oldPoint);
Да и даже без возможности толкания героя в случае, когда на эту же позицию попадет монстр - последний будет просто удален.

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		characters.put(newPoint, user);
Здесь, в принципе, тоже

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public Point getPointUser() {
Не очень красиво на каждое нажатие вычислять позицию героя. Это удобнее либо вообще хранить отдельно, либо поддерживать прокси на значение в мапе.

2021-06-02 15:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public TreasureHunter<MoveBehavior> getUser() {
Ты же вместе с позицией его получил в getPointUser. Зачем еще раз искать?

2021-06-03 08:27 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public void changePositionUser(Point oldPoint, Point newPoint) {
Ну, я думал ты имел ввиду движение персонажа игроком,  а не то, что его еще могут толкать и перемещать его.

2021-06-03 09:45 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		characters.remove(oldPoint);
Значит сперва пусть будет удалена старая позиция героя, а потом уже пуст появится монстр.

2021-06-03 12:30 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +    		if (!(value instanceof TreasureHunter<?>)) {
Нет, это проблему не решит. У тебя конкурентный доступ к мапе с позициями и персонажами

2021-06-03 12:30 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public void changePositionUser(Point oldPoint, Point newPoint) {
Да, я именно про это: текущую реализацию надо будет менять сразу, как только героя начнут перемещать иначе, чем по нажатию кнопки

2021-06-03 12:32 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +		characters.remove(oldPoint);
В условиях конкурентного доступа "сначала" и "потом" могут непредсказуемо меняться. Ты же не останавливаешь потоки, управляющие монстрами, когда жмешь на кнопку? Вот в любой момент между нажатием и фактическим перемещением значение в мапе по ключу может измениться

2021-06-03 12:36 UTC, Agny requested changes

2021-06-03 12:36 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/level/map/room/Room.java
> +		initPointUser();
И что изменилось? Ты по прежнему на каждое нажатие заново ищешь позицию персонажа

2021-06-05 14:37 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public void changePositionUser(Point oldPoint, Point newPoint) {
Слушай, чет не кружусь над этим методом и не знаю, как сделать, чтобы ГГ можно было толкать. 
Зарисовал примерно как всё должно происходить, но реализовать не выходит.

2021-06-05 16:14 UTC, Agny requested changes

2021-06-05 16:14 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +		System.out.println();
Что за систем ауты опять?

2021-06-05 16:14 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/controller/UserKeys.java
> +				if (!gameLoop.isPause()) {
Не похоже, что почти весь кусок повторяется и при нажатии на A?

2021-06-05 16:17 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/game/GameLoop.java
> +	public void changePositionUser(Point oldPoint, Point newPoint) {
Коллизии потом реализовывать будем. Просто текущая твоя схема не очень хорошо под них подходит в принципе

2021-06-05 17:18 UTC, merged