Task add gravitation
fadedFog/Tombs pull request #9
Opened 2021-07-17 13:13 UTC by fadedFog

2021-07-17 18:05 UTC, Agny requested changes

2021-07-17 18:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/MoveBehavior.java
> +	void setBoostZero();
И в чем смысл?

2021-07-17 18:05 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/MoveBehavior.java
> +	static final int GRAVITATION = -1;
В мувбехивиор с гравитацей надо работать, а не хранить. Сделай класс, в котором будут настройки уровня лежать, там ее и храни.

Имей в виду такой возможный сценарий работы: игрок подбирает предмет/использует способность и гравитация на уровне пропадает на какое-то время. Или наоборот, удваивается. Реализуй с учетом этого.

2021-07-18 09:55 UTC, fadedFog commented on app/src/main/java/ru/fadedfog/tombs/asset/character/behavior/move/MoveBehavior.java
> +	void setBoostZero();
Я подумал, что будет удобно сразу обнулять ускорения падения объекта. Например, когда объект становиться на поверхность. Уберу, значит.

2021-07-18 19:03 UTC, Agny approved these changes

2021-07-18 19:03 UTC, Agny commented on app/src/main/java/ru/fadedfog/tombs/settings/SettingsGame.java
> +	public static final int ZERO = 0;
Все эти статики не нужны

2021-07-18 19:15 UTC, merged